### ISSUE TITLE
IndentationError: unexpected unindent

### ISSUE THREAD

**Issue by BH1SCW** [fky2015/reportMyIP#1]
serverSide:

$ python3 main.py
  File "main.py", line 17
    def wrap_list(ls: list) -> dict:
    ^
IndentationError: unexpected unindent

**Comment by fky2015** [comment]
I'm sorry for not getting back to you sooner.

This error was caused by an old, erroneous syntax that I used. I fixed it in the commit with the hash cb0b5ff27954bb5d0a6671355b112a6bef4bdb1a.

However, please be aware that this is a very immature and unmaintained project that should only be used for educational purposes.

**Comment by BH1SCW** [comment]
Great thanks~
